# Nome da aplica��o
spring.application.name=Aluno Online

# Conex�o com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aluno_online_2026
spring.datasource.username=postgres
spring.datasource.password=091020
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: cria/atualiza tabelas automaticamente!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Usa uma linha em branco dupla no data.sql como separador de comandos, em vez do ponto e v�rgula
spring.sql.init.separator=^^
